import { PillarPageData } from './local-seo-data';

/**
 * 16 additional money pages – brings total to 28 (7 per city × 4 cities).
 * Uses the exact PillarPageData interface from local-seo-data.ts:
 *   stats (not heroStats), processSteps (not process),
 *   benefits WITHOUT icon, caseStudy { result, description, m1, m1Label, m2, m2Label }
 */
export const extraPillarPages: PillarPageData[] = [

  /* ── BREMEN (+1) ────────────────────────────────────────────────────────── */
  {
    slug: 'prozessautomatisierung-bremen',
    service: 'Prozessautomatisierung',
    city: 'Bremen',
    metaTitle: 'Prozessautomatisierung Bremen – Workflows automatisieren | Northcode',
    metaDescription: 'Prozessautomatisierung für Unternehmen in Bremen: Workflows, Datensynchronisation & Reporting automatisieren. Effizienz steigern, Kosten senken. Jetzt anfragen!',
    h1: 'Prozessautomatisierung in Bremen',
    subtitle: 'Manuelle Workflows eliminieren – Effizienz systematisch steigern.',
    intro: 'Bremer Unternehmen verlieren täglich Stunden durch manuelle, sich wiederholende Prozesse: Dateneingabe, Berichterstattung, Genehmigungsworkflows, Kundenkommunikation. Northcode analysiert Ihre Prozesslandschaft und automatisiert die größten Zeitfresser – schnell, messbar und ohne IT-Overhead.',
    stats: [
      { value: '70 %', label: 'weniger manuelle Aufgaben' },
      { value: '< 4 Wo', label: 'bis zur ersten Automatisierung live' },
      { value: '5×', label: 'typischer ROI im ersten Jahr' },
      { value: '0 €', label: 'Erstgespräch & Potenzialanalyse' },
    ],
    services: [
      { icon: '🔄', title: 'Workflow-Automatisierung', desc: 'Manuelle Abläufe zwischen Systemen automatisch orchestrieren – von der Auftragseingabe bis zur Rechnung.' },
      { icon: '📊', title: 'Automatisiertes Reporting', desc: 'Kennzahlen und Berichte aus mehreren Quellen täglich automatisch generieren und verteilen.' },
      { icon: '🔗', title: 'System-Integration', desc: 'ERP, CRM, Shop und Buchhaltung sprechen automatisch miteinander – kein manuelles Datenpflegen mehr.' },
      { icon: '🤖', title: 'KI-gestützte Entscheidungen', desc: 'Automatische Klassifizierung, Priorisierung und Weiterleitung von Anfragen und Dokumenten per KI.' },
    ],
    benefits: [
      { title: 'Sofort spürbar', desc: 'Erste automatisierte Prozesse gehen innerhalb von Wochen live – messbare Zeitersparnis vom ersten Tag.' },
      { title: 'Fehlerfrei', desc: 'Automatisierte Prozesse sind konsistent – keine Übertragungsfehler, keine vergessenen Schritte.' },
      { title: 'Skalierbar', desc: 'Das Automatisierungssystem wächst mit Ihrem Unternehmen mit – ohne proportional mehr Personal.' },
      { title: 'Wartungsarm', desc: 'Northcode übernimmt Monitoring und Wartung – Ihr Team muss sich um nichts kümmern.' },
    ],
    processSteps: [
      { step: 1, title: 'Prozess-Audit', desc: 'Analyse Ihrer aktuellen Workflows und Identifikation der größten Automatisierungspotenziale in Bremen.' },
      { step: 2, title: 'Priorisierung & Konzept', desc: 'Wir priorisieren nach ROI – welche Prozesse bringen die größte Zeitersparnis pro Aufwand?' },
      { step: 3, title: 'Entwicklung & Integration', desc: 'Bau der Automatisierungen mit Anbindung an Ihre bestehenden Systeme (ERP, CRM, Mail, etc.).' },
      { step: 4, title: 'Go-Live & Schulung', desc: 'Schrittweiser Live-Gang mit vollständiger Team-Schulung ohne Betriebsunterbrechung.' },
    ],
    caseStudy: {
      result: 'Bremer Logistikdienstleister automatisiert Auftragsverarbeitung',
      description: 'Ein Logistikdienstleister aus Bremen verarbeitete Aufträge manuell in 4 Stunden täglich. Nach der Automatisierung durch Northcode dauert derselbe Prozess unter 20 Minuten – ohne neues Personal und ohne neue Software.',
      m1: '87 %', m1Label: 'Zeitersparnis Auftragsverarbeitung',
      m2: '4 Wo', m2Label: 'bis zum vollautomatischen Betrieb',
    },
    faqs: [
      { question: 'Welche Prozesse lassen sich in einem Bremer Unternehmen automatisieren?',
        answer: 'Praktisch alle wiederkehrenden, regelbasierten Aufgaben: Auftragsverarbeitung, Rechnungsstellung, Reporting, Datensynchronisation, E-Mail-Workflows, Genehmigungsprozesse, Datenbankpflege und mehr.' },
      { question: 'Was kostet Prozessautomatisierung in Bremen?',
        answer: 'Einfache Automatisierungen starten ab ca. 800 €. Komplexe Multi-System-Workflows liegen bei 3.000–8.000 €. Im kostenlosen Erstgespräch erstellen wir eine genaue Kalkulation.' },
      { question: 'Muss ich meine bestehende Software wechseln?',
        answer: 'Nein. Northcode integriert in Ihre bestehende Systemlandschaft – egal ob SAP, DATEV, Salesforce oder proprietäre Systeme. Der Wechsel zu neuer Software ist selten notwendig.' },
    ],
    relatedPages: [
      { title: 'KI-Automatisierung Bremen', href: '/ki-automatisierung-bremen' },
      { title: 'CRM Software Bremen', href: '/crm-software-bremen' },
      { title: 'Leadgenerierung Bremen', href: '/leadgenerierung-bremen' },
      { title: 'Digitalisierung Bremen', href: '/digitalisierung-bremen' },
      { title: 'Prozessautomatisierung Oldenburg', href: '/prozessautomatisierung-oldenburg' },
    ],
  },

  /* ── OLDENBURG (+4) ─────────────────────────────────────────────────────── */
  {
    slug: 'digitalisierung-oldenburg',
    service: 'Digitalisierung',
    city: 'Oldenburg',
    metaTitle: 'Digitalisierung Oldenburg – KMU digital transformieren | Northcode',
    metaDescription: 'Digitalisierung für Unternehmen in Oldenburg: Cloud, Prozessoptimierung & digitale Infrastruktur. Schritt für Schritt – mit Förderberatung. Jetzt starten!',
    h1: 'Digitalisierung in Oldenburg',
    subtitle: 'Schritt für Schritt digital – ohne Chaos und Überforderung.',
    intro: 'Die Digitalisierung ist für Unternehmen in Oldenburg keine Frage des Ob, sondern des Wie. Northcode begleitet Oldenburger KMU Schritt für Schritt durch die Transformation – mit klarem Plan, messbaren Ergebnissen und Unterstützung bei Fördermitteln.',
    stats: [
      { value: '40 %', label: 'Effizienzgewinn im Schnitt' },
      { value: '100+', label: 'digitalisierte Prozesse' },
      { value: '15–40 %', label: 'Förderquote möglich' },
      { value: '0 €', label: 'Erstgespräch & Fördercheck' },
    ],
    services: [
      { icon: '☁️', title: 'Cloud-Migration', desc: 'Datenmigration zu sicheren, effizienten Cloud-Lösungen – Microsoft 365, Google Workspace oder eigene Cloud.' },
      { icon: '📋', title: 'Prozess-Digitalisierung', desc: 'Analoge Prozesse Schritt für Schritt digitalisieren – von der Eingangspost bis zum Archiv.' },
      { icon: '📱', title: 'Mobile Working', desc: 'Mitarbeiter arbeiten sicher von überall – mit richtigen Tools, Richtlinien und IT-Infrastruktur.' },
      { icon: '🔌', title: 'System-Konsolidierung', desc: 'Bestehende Software-Silos zusammenführen – eine zentrale Plattform statt zehn Einzellösungen.' },
    ],
    benefits: [
      { title: 'Messbar effizienter', desc: 'Digitale Prozesse sind schneller, günstiger und fehlerarmer als analoge Abläufe.' },
      { title: 'Zukunftssicher', desc: 'Eine gute digitale Grundlage ermöglicht spätere Erweiterungen (KI, Automatisierung) ohne Umbau.' },
      { title: 'Förderbar', desc: 'Bis zu 40 % der Investitionskosten sind durch Bundesförderprogramme erstattungsfähig.' },
      { title: 'Persönlich begleitet', desc: 'Northcode ist vor Ort in Oldenburg – persönliche Beratung, kein Call-Center.' },
    ],
    processSteps: [
      { step: 1, title: 'Ist-Analyse', desc: 'Bestandsaufnahme aller aktuellen Prozesse, Systeme und Schwachstellen in Ihrem Oldenburger Unternehmen.' },
      { step: 2, title: 'Digitalisierungs-Roadmap', desc: 'Priorisierter Plan mit Quick Wins und strategischen Maßnahmen – klar kommuniziert, realistisch umsetzbar.' },
      { step: 3, title: 'Förderantrag', desc: 'Identifikation passender Förderprogramme (Digital Jetzt, Niedersachsen-Förderung) und Unterstützung bei der Antragstellung.' },
      { step: 4, title: 'Umsetzung & Schulung', desc: 'Iterative Implementierung und Schulung aller Mitarbeiter – damit neue Systeme auch wirklich genutzt werden.' },
    ],
    caseStudy: {
      result: 'Oldenburger Handelsbetrieb – vollständiges digitales Büro in 6 Wochen',
      description: 'Ein Händler aus Oldenburg arbeitete noch vollständig analog mit Papierprozessen. Nach 6 Wochen Digitalisierungsprojekt mit Northcode: 60 % weniger Papierdokumente, 30 % schnellere Auftragsabwicklung, 3.800 € Fördermittel erhalten.',
      m1: '60 %', m1Label: 'weniger Papierprozesse',
      m2: '6 Wo', m2Label: 'bis zum digitalen Büro',
    },
    faqs: [
      { question: 'Wo fange ich mit der Digitalisierung in meinem Oldenburger Unternehmen an?',
        answer: 'Am besten bei dem Prozess, der Sie täglich am meisten Zeit kostet. Northcode hilft beim Priorisieren – im kostenlosen Erstgespräch analysieren wir gemeinsam Ihr größtes Potenzial.' },
      { question: 'Welche Fördermittel gibt es für Digitalisierung in Oldenburg?',
        answer: 'Das Bundesförderprogramm "Digital Jetzt" bietet 15–40 % Förderquote. Northcode prüft kostenlos, welche Fördermittel für Sie in Frage kommen.' },
    ],
    relatedPages: [
      { title: 'Digitalisierung Bremen', href: '/digitalisierung-bremen' },
      { title: 'Digitalisierung Verwaltung Oldenburg', href: '/digitalisierung-verwaltung-oldenburg' },
      { title: 'Workflow-Automatisierung Oldenburg', href: '/workflow-automatisierung-oldenburg' },
      { title: 'KI-Beratung Oldenburg', href: '/ki-beratung-oldenburg' },
      { title: 'Digitalisierung Kosten Oldenburg', href: '/digitalisierung-kosten-oldenburg' },
    ],
  },

  {
    slug: 'prozessautomatisierung-oldenburg',
    service: 'Prozessautomatisierung',
    city: 'Oldenburg',
    metaTitle: 'Prozessautomatisierung Oldenburg – Workflows automatisieren | Northcode',
    metaDescription: 'Prozessautomatisierung für Unternehmen in Oldenburg: Manuelle Workflows eliminieren, Systeme verbinden & Effizienz steigern. Jetzt beraten lassen!',
    h1: 'Prozessautomatisierung in Oldenburg',
    subtitle: 'Routineaufgaben eliminieren – Ihr Team konzentriert sich auf das Wesentliche.',
    intro: 'Unternehmen in Oldenburg und der Weser-Ems-Region verlieren wertvolle Kapazitäten durch manuelle, fehleranfällige Routineprozesse. Northcode analysiert, priorisiert und automatisiert – messbar, schnell und ohne Betriebsunterbrechung.',
    stats: [
      { value: '75 %', label: 'weniger Routineaufgaben' },
      { value: '2–4 Wo', label: 'bis zur ersten Live-Automatisierung' },
      { value: '5×', label: 'ROI typisch im ersten Jahr' },
      { value: '0 €', label: 'Erstgespräch & Potenzialanalyse' },
    ],
    services: [
      { icon: '🔄', title: 'Workflow-Automatisierung', desc: 'Manuelle Abläufe zwischen Systemen automatisch orchestrieren.' },
      { icon: '🔌', title: 'System-Integrationen', desc: 'CRM, ERP, Shop und Buchhaltung automatisch synchronisieren.' },
      { icon: '📊', title: 'Automatisches Reporting', desc: 'KPIs und Berichte täglich automatisch generieren und verteilen.' },
      { icon: '🤖', title: 'KI-Routing & Klassifizierung', desc: 'Eingehende Anfragen automatisch priorisieren und weiterleiten.' },
    ],
    benefits: [
      { title: 'Schnelle Ergebnisse', desc: 'Erste Automatisierungen sind in 2–3 Wochen live – sofortige Zeitersparnis messbar.' },
      { title: 'Nullfehler-Prozesse', desc: 'Automatisierte Abläufe sind konsistenter und fehlerarmer als manuelle Prozesse.' },
      { title: 'Skalierbares Wachstum', desc: 'Mehr Auftragsvolumen ohne mehr Personal – dank automatisierter Kapazitäten.' },
      { title: 'Geringer Wartungsaufwand', desc: 'Northcode überwacht und wartet alle Automatisierungen dauerhaft.' },
    ],
    processSteps: [
      { step: 1, title: 'Prozess-Analyse', desc: 'Bestandsaufnahme aller Workflows in Ihrem Oldenburger Unternehmen.' },
      { step: 2, title: 'ROI-Priorisierung', desc: 'Welche Automatisierungen bringen den größten Nutzen pro Investition?' },
      { step: 3, title: 'Entwicklung', desc: 'Bau der Automatisierungen mit nahtloser Integration in Ihre Bestandssysteme.' },
      { step: 4, title: 'Go-Live & Monitoring', desc: 'Schrittweiser Live-Gang mit vollständiger Schulung und kontinuierlichem Monitoring.' },
    ],
    caseStudy: {
      result: 'Oldenburger Dienstleistungsunternehmen – Antwortzeit von 24h auf unter 5 Minuten',
      description: 'Ein Dienstleister aus Oldenburg bearbeitete eingehende Kundenanfragen manuell – Antwortzeit durchschnittlich 24 Stunden. Nach KI-gestützter Automatisierung werden Standardanfragen in unter 5 Minuten beantwortet, komplexe Fälle intelligent weitergeleitet.',
      m1: '95 %', m1Label: 'schnellere Antwortzeiten',
      m2: '3 Wo', m2Label: 'bis zum automatisierten Prozess',
    },
    faqs: [
      { question: 'Was kostet Prozessautomatisierung in Oldenburg?',
        answer: 'Einfache Automatisierungen ab 900 €. Komplexe Multi-System-Workflows 3.000–7.000 €. Im kostenlosen Erstgespräch erhalten Sie eine konkrete Kalkulation für Ihre Anforderungen.' },
      { question: 'Muss ich neue Software kaufen?',
        answer: 'Nein. Northcode integriert in Ihre bestehenden Systeme – egal welche Software Sie in Oldenburg einsetzen.' },
    ],
    relatedPages: [
      { title: 'Prozessautomatisierung Bremen', href: '/prozessautomatisierung-bremen' },
      { title: 'CRM Systeme Oldenburg', href: '/crm-systeme-oldenburg' },
      { title: 'Workflow-Automatisierung Oldenburg', href: '/workflow-automatisierung-oldenburg' },
      { title: 'Automatisierung Produktionsbetriebe Oldenburg', href: '/automatisierung-produktionsbetriebe-oldenburg' },
      { title: 'KI-Automatisierung Oldenburg', href: '/ki-automatisierung-oldenburg' },
    ],
  },

  {
    slug: 'unternehmenssysteme-oldenburg',
    service: 'Unternehmenssysteme',
    city: 'Oldenburg',
    metaTitle: 'Unternehmenssysteme Oldenburg – ERP & Business-Software | Northcode',
    metaDescription: 'Individuelle Unternehmenssysteme für Oldenburg: ERP, CRM, Warenwirtschaft & Business-Software maßgeschneidert. Kein Lizenz-Abo – eigene Lösung. Jetzt anfragen!',
    h1: 'Unternehmenssysteme in Oldenburg',
    subtitle: 'Business-Software, die zu Ihrem Unternehmen passt – nicht umgekehrt.',
    intro: 'Standard-Software wie SAP, Salesforce oder HubSpot kostet viel und passt selten perfekt. Northcode entwickelt individuelle Unternehmenssysteme für Oldenburger KMU – exakt auf Ihre Prozesse zugeschnitten, ohne monatliche Lizenzgebühren.',
    stats: [
      { value: '100 %', label: 'auf Ihren Prozess zugeschnitten' },
      { value: '0 €', label: 'monatliche Lizenzgebühren' },
      { value: '4–8 Wo', label: 'bis zur ersten Version live' },
      { value: '10+', label: 'Systeme entwickelt in der Region' },
    ],
    services: [
      { icon: '🏢', title: 'ERP-Entwicklung', desc: 'Maßgeschneidertes Enterprise-Resource-Planning – Lager, Einkauf, Verkauf, Produktion in einer Lösung.' },
      { icon: '🔗', title: 'CRM-System', desc: 'Kundenverwaltung, Pipeline und Kommunikation – gebaut nach Ihrem Vertriebsprozess.' },
      { icon: '📦', title: 'Warenwirtschaft', desc: 'Bestandsverwaltung, Lieferanten und Bestellungen – vollintegriert mit Buchführung.' },
      { icon: '📊', title: 'Business Intelligence', desc: 'Dashboards und Reports mit Echtzeit-Daten aus allen Unternehmensbereichen.' },
    ],
    benefits: [
      { title: 'Passgenaue Lösung', desc: 'Software, die Ihren Prozess unterstützt – nicht Sie zwingt, sich an die Software anzupassen.' },
      { title: 'Keine Lizenzkosten', desc: 'Einmalige Entwicklungskosten – das System gehört Ihnen, für immer, ohne Abonnement.' },
      { title: 'Volle Integration', desc: 'Nahtlose Anbindung an bestehende Tools: DATEV, Mailsysteme, Webshops und mehr.' },
      { title: 'Skalierbar', desc: 'Das System wächst mit Ihrem Oldenburger Unternehmen – neue Funktionen auf Abruf.' },
    ],
    processSteps: [
      { step: 1, title: 'Anforderungsaufnahme', desc: 'Ausführliches Briefing Ihrer Prozesse, Anforderungen und Wünsche.' },
      { step: 2, title: 'Systemarchitektur', desc: 'Konzeption der optimalen technischen Lösung für Ihren Anwendungsfall.' },
      { step: 3, title: 'Iterative Entwicklung', desc: 'Entwicklung in Sprints – Sie sehen früh erste Ergebnisse und können mitgestalten.' },
      { step: 4, title: 'Go-Live & Support', desc: 'Schrittweiser Live-Gang, Datenmigration, Schulung und dauerhafter Support durch Northcode.' },
    ],
    caseStudy: {
      result: 'Oldenburger Großhändler – Warenwirtschaft und CRM in einem System',
      description: 'Ein Großhändler aus Oldenburg pflegte Bestellungen, Kunden und Lager in drei separaten Systemen. Northcode entwickelte ein integriertes Unternehmenssystem – die Auftragsabwicklung wurde 3× schneller, Buchungsfehler verschwanden vollständig.',
      m1: '3×', m1Label: 'schnellere Auftragsabwicklung',
      m2: '0', m2Label: 'Buchungsfehler nach Migration',
    },
    faqs: [
      { question: 'Wann lohnt sich ein individuelles Unternehmenssystem statt einer Standard-Lösung in Oldenburg?',
        answer: 'Wenn Ihre Prozesse komplexer sind als Standard-Software abbilden kann, wenn Sie mehr als 5 Nutzer haben und wenn die jährlichen Lizenzkosten die Entwicklungskosten in 2–3 Jahren überschreiten.' },
      { question: 'Wie lange dauert die Entwicklung?',
        answer: 'Erste funktionsfähige Version: 4–8 Wochen. Vollständige Lösung: 8–20 Wochen – je nach Komplexität.' },
    ],
    relatedPages: [
      { title: 'Unternehmenssysteme Bremen', href: '/unternehmenssysteme-bremen' },
      { title: 'CRM Systeme Oldenburg', href: '/crm-systeme-oldenburg' },
      { title: 'ERP-Beratung Oldenburg', href: '/erp-beratung-oldenburg' },
      { title: 'KI-Beratung Oldenburg', href: '/ki-beratung-oldenburg' },
    ],
  },

  {
    slug: 'backend-entwicklung-oldenburg',
    service: 'Backend-Entwicklung',
    city: 'Oldenburg',
    metaTitle: 'Backend-Entwicklung Oldenburg – APIs & Server-Systeme | Northcode',
    metaDescription: 'Professionelle Backend-Entwicklung für Unternehmen in Oldenburg: APIs, Datenbanken & Server-Architekturen. Skalierbar & zukunftssicher. Jetzt anfragen!',
    h1: 'Backend-Entwicklung in Oldenburg',
    subtitle: 'Das technische Fundament für skalierbare Geschäftssysteme.',
    intro: 'Moderne Geschäftsanwendungen brauchen ein solides technisches Fundament: performante APIs, skalierbare Datenbanken und sichere Server-Architekturen. Northcode entwickelt Backend-Systeme für Oldenburger Unternehmen – mit Technologien, die langfristig tragen.',
    stats: [
      { value: '99,9 %', label: 'angestrebte Uptime-Garantie' },
      { value: '< 200ms', label: 'API-Antwortzeit (Zielwert)' },
      { value: '10+', label: 'Backend-Systeme ausgeliefert' },
      { value: '0 €', label: 'Erstgespräch & Systemcheck' },
    ],
    services: [
      { icon: '🔗', title: 'REST & GraphQL APIs', desc: 'Skalierbare API-Architekturen für Web-Apps, Mobile Apps und System-Integrationen.' },
      { icon: '🗄️', title: 'Datenbank-Design', desc: 'Optimierte Datenbankstrukturen für Performance, Skalierbarkeit und Datensicherheit.' },
      { icon: '☁️', title: 'Cloud-Infrastruktur', desc: 'AWS, Azure oder Hetzner – Serverarchitektur für maximale Uptime und Kosteneffizienz.' },
      { icon: '🛡️', title: 'Security & Compliance', desc: 'DSGVO-konformes Backend mit End-to-End-Verschlüsselung, Zugriffskontrollen und Audit-Logs.' },
    ],
    benefits: [
      { title: 'Hochperformant', desc: 'Optimierte Queries und Caching-Strategien für blitzschnelle Antwortzeiten.' },
      { title: 'Sicher by Design', desc: 'Sicherheit von Anfang an – keine Schwachstellen durch schnelle Entwicklung.' },
      { title: 'Skalierbar', desc: 'Architektur, die von 10 auf 100.000 Nutzer skaliert – ohne Neubau.' },
      { title: 'Wartbar', desc: 'Sauberer, dokumentierter Code – kein Vendor-Lock-in, einfach erweiterbar.' },
    ],
    processSteps: [
      { step: 1, title: 'Anforderungsanalyse', desc: 'Klärung der technischen Anforderungen, Schnittstellen und Skalierungsziele.' },
      { step: 2, title: 'Architekturdesign', desc: 'Auswahl der optimalen Technologien und Systemarchitektur für Ihren Anwendungsfall.' },
      { step: 3, title: 'Entwicklung & Testing', desc: 'Iterative Entwicklung: Unit-, Integration-, Performance- und Security-Tests.' },
      { step: 4, title: 'Deployment & Monitoring', desc: 'Live-Schaltung auf skalierbarer Infrastruktur mit 24/7 Monitoring.' },
    ],
    caseStudy: {
      result: 'Oldenburger SaaS-Startup – API-Performance vervierfacht',
      description: 'Ein SaaS-Startup aus Oldenburg litt unter langsamen API-Antworten (Ø 800ms) und regelmäßigen Ausfällen bei mehr Last. Northcode redesignte die Backend-Architektur – Antwortzeiten sanken auf unter 200ms, das System skaliert jetzt auf 10× mehr Nutzer ohne Mehrkosten.',
      m1: '4×', m1Label: 'schnellere API-Antworten',
      m2: '10×', m2Label: 'mehr Nutzer ohne Mehrkosten',
    },
    faqs: [
      { question: 'Welche Technologien nutzt Northcode für Backend-Entwicklung in Oldenburg?',
        answer: 'Node.js (TypeScript), Python (FastAPI/Django), PostgreSQL, Redis, Docker und Kubernetes – je nach Anforderung. Wir empfehlen immer die bewährteste Lösung für Ihren Anwendungsfall.' },
      { question: 'Was kostet Backend-Entwicklung in Oldenburg?',
        answer: 'Einfache REST API: ab 2.000 €. Komplexe Backend-Systeme: 8.000–25.000 €. Infrastrukturkosten separat (ab ca. 30 €/Monat).' },
    ],
    relatedPages: [
      { title: 'Backend-Entwicklung Bremen', href: '/backend-entwicklung-bremen' },
      { title: 'Unternehmenssysteme Oldenburg', href: '/unternehmenssysteme-oldenburg' },
      { title: 'KI-Beratung Oldenburg', href: '/ki-beratung-oldenburg' },
    ],
  },

  /* ── DELMENHORST (+5) ───────────────────────────────────────────────────── */
  {
    slug: 'ki-automatisierung-delmenhorst',
    service: 'KI-Automatisierung',
    city: 'Delmenhorst',
    metaTitle: 'KI-Automatisierung Delmenhorst – Workflows mit KI optimieren | Northcode',
    metaDescription: 'KI-Automatisierung für Unternehmen in Delmenhorst: Chatbots, Dokumentenverarbeitung & Workflow-Automatisierung. Effizienz steigern. Jetzt beraten lassen!',
    h1: 'KI-Automatisierung in Delmenhorst',
    subtitle: 'Künstliche Intelligenz für smarte Workflows in Ihrem Unternehmen.',
    intro: 'KI-Automatisierung ermöglicht Delmenhorster Unternehmen, repetitive Aufgaben vollständig zu eliminieren – Chatbots beantworten Kundenanfragen, KI verarbeitet Dokumente und Workflows laufen automatisch. Northcode baut maßgeschneiderte KI-Lösungen für die Region.',
    stats: [
      { value: '80 %', label: 'der Routineaufgaben automatisierbar' },
      { value: '2–3 Mo', label: 'typische Amortisationszeit' },
      { value: '24/7', label: 'KI arbeitet ohne Pause' },
      { value: '0 €', label: 'Erstgespräch & KI-Check' },
    ],
    services: [
      { icon: '🤖', title: 'KI-Chatbots', desc: 'Intelligente Chatbots für Website, WhatsApp oder App – beantworten Anfragen rund um die Uhr.' },
      { icon: '📂', title: 'Dokument-KI', desc: 'Belege, Rechnungen und Verträge automatisch erkennen, klassifizieren und verarbeiten.' },
      { icon: '🔄', title: 'Workflow-Automation', desc: 'Geschäftsprozesse automatisch steuern – von der Anfrage bis zur Lieferung.' },
      { icon: '📊', title: 'Predictive Analytics', desc: 'KI-basierte Vorhersagen für Nachfrage, Auslastung und Risiken.' },
    ],
    benefits: [
      { title: 'Rund um die Uhr', desc: 'KI-Systeme arbeiten 24/7 – ohne Urlaub, Krankheit oder Mittagspause.' },
      { title: 'Lernend', desc: 'Moderne KI-Systeme verbessern sich mit jedem Einsatz automatisch.' },
      { title: 'Kosteneffizient', desc: 'Einmalige Implementierung – dauerhaft günstigere Prozesskosten als manuelle Arbeit.' },
      { title: 'Integrierbar', desc: 'Nahtlose Integration in bestehende Systeme ohne Unterbrechung des Betriebs.' },
    ],
    processSteps: [
      { step: 1, title: 'KI-Potenzialanalyse', desc: 'Identifikation der Prozesse in Delmenhorst mit dem größten KI-Automatisierungspotenzial.' },
      { step: 2, title: 'Lösung konzipieren', desc: 'Auswahl der optimalen KI-Technologien für Ihren Anwendungsfall.' },
      { step: 3, title: 'Entwicklung & Training', desc: 'Bau und Training der KI-Systeme mit Ihren eigenen Daten.' },
      { step: 4, title: 'Integration & Schulung', desc: 'Einbindung in bestehende Systeme und vollständige Mitarbeiterschulung.' },
    ],
    caseStudy: {
      result: 'Delmenhorster Handelsunternehmen – 85 % der Kundenanfragen automatisiert',
      description: 'Ein Handelsunternehmen aus Delmenhorst erhielt täglich Dutzende gleichartige Kundenanfragen. Nach Einführung eines KI-Chatbots durch Northcode werden 85 % vollautomatisch beantwortet – die Kundenzufriedenheit stieg auf 4,8/5.',
      m1: '85 %', m1Label: 'Anfragen automatisch beantwortet',
      m2: '4,8/5', m2Label: 'Kundenzufriedenheit',
    },
    faqs: [
      { question: 'Ist KI auch für kleine Unternehmen in Delmenhorst erschwinglich?',
        answer: 'Ja. Einfache KI-Lösungen wie ein Chatbot oder automatische E-Mail-Klassifizierung starten ab 600–1.000 €. Der ROI ist bei kleinen Betrieben oft am schnellsten spürbar.' },
      { question: 'Brauche ich technische Vorkenntnisse für KI-Systeme?',
        answer: 'Nein. Northcode übernimmt die gesamte technische Umsetzung und Schulung – Ihre Mitarbeiter bedienen die KI über einfache Benutzeroberflächen.' },
    ],
    relatedPages: [
      { title: 'KI-Automatisierung Bremen', href: '/ki-automatisierung-bremen' },
      { title: 'KI für Handwerker Delmenhorst', href: '/ki-fuer-handwerker-delmenhorst' },
      { title: 'KI für Gastronomie Delmenhorst', href: '/ki-fuer-gastronomie-delmenhorst' },
      { title: 'Kundenanfragen automatisieren Delmenhorst', href: '/kundenanfragen-automatisieren-delmenhorst' },
      { title: 'KI-Kosten Bremen', href: '/ki-kosten-bremen' },
    ],
  },

  {
    slug: 'webdesign-delmenhorst',
    service: 'Webdesign',
    city: 'Delmenhorst',
    metaTitle: 'Webdesign Delmenhorst – Professionelle Websites für KMU | Northcode',
    metaDescription: 'Professionelles Webdesign für Unternehmen in Delmenhorst: moderne, schnelle Websites mit SEO und mobilem Design. Persönliche Betreuung. Jetzt anfragen!',
    h1: 'Webdesign in Delmenhorst',
    subtitle: 'Websites, die verkaufen – nicht nur gut aussehen.',
    intro: 'Delmenhorster Unternehmen brauchen Websites, die lokal gefunden werden, auf dem Smartphone perfekt aussehen und Besucher zu Kunden machen. Northcode entwickelt Websites mit Conversion-Fokus – modern, schnell und SEO-optimiert für die Region.',
    stats: [
      { value: '100+', label: 'Websites realisiert in der Region' },
      { value: '< 3 Sek', label: 'Ladezeit-Ziel (Core Web Vitals)' },
      { value: '3×', label: 'höhere Conversion-Rate im Schnitt' },
      { value: '0 €', label: 'Erstgespräch & Design-Briefing' },
    ],
    services: [
      { icon: '💻', title: 'Business-Websites', desc: 'Professionelle Unternehmenswebsites mit klarer Struktur, starkem Design und überzeugenden Texten.' },
      { icon: '🎯', title: 'Landingpages', desc: 'Conversion-optimierte Seiten für spezifische Kampagnen, Produkte oder Services.' },
      { icon: '🛒', title: 'Onlineshops', desc: 'Shopify-Shops für lokale Händler in Delmenhorst – schnell, sicher und skalierbar.' },
      { icon: '🔍', title: 'SEO-Optimierung', desc: 'Lokale SEO-Grundoptimierung für wichtige Delmenhorster Keywords inklusive.' },
    ],
    benefits: [
      { title: 'Lokal auffindbar', desc: 'SEO-Grundoptimierung für wichtige Delmenhorster Keywords inklusive.' },
      { title: 'Mobil perfekt', desc: 'Über 70 % der Suchanfragen in Delmenhorst kommen vom Smartphone.' },
      { title: 'Schnell', desc: 'Optimierte Ladezeiten für bessere Rankings und mehr Conversions.' },
      { title: 'Pflegeleicht', desc: 'CMS-Zugang – Texte und Bilder selbst aktualisieren, ohne Programmierkenntnisse.' },
    ],
    processSteps: [
      { step: 1, title: 'Briefing', desc: 'Kennenlernen, Ziele klären, Zielgruppe in Delmenhorst definieren und Wettbewerb analysieren.' },
      { step: 2, title: 'Konzept & Design', desc: 'Wireframes und Design-Entwürfe – Sie sehen früh, wohin die Reise geht.' },
      { step: 3, title: 'Entwicklung & SEO', desc: 'Technische Umsetzung mit modernsten Standards und SEO-Grundeinrichtung.' },
      { step: 4, title: 'Launch', desc: 'Go-Live, Google-Anmeldung und 30 Tage Nachbetreuung inklusive.' },
    ],
    caseStudy: {
      result: 'Delmenhorster Handwerksbetrieb – 3–5 neue Anfragen pro Woche über Google',
      description: 'Ein Handwerksbetrieb aus Delmenhorst hatte keine eigene Website. Northcode entwickelte eine mobiloptimierte Business-Website mit lokaler SEO – innerhalb von 3 Monaten stieg der organische Traffic um 280 %, der Betrieb erhält seitdem 3–5 Anfragen pro Woche über Google.',
      m1: '+280 %', m1Label: 'organischer Traffic nach 3 Monaten',
      m2: '3–5/Wo', m2Label: 'neue Anfragen über Website',
    },
    faqs: [
      { question: 'Was kostet eine professionelle Website in Delmenhorst?',
        answer: 'Einfache Visitenkartenseiten ab 390 €. Business-Websites mit SEO ab 900 €. Im kostenlosen Erstgespräch erhalten Sie ein transparentes Festpreisangebot ohne versteckte Kosten.' },
      { question: 'Wie lange dauert die Website-Erstellung in Delmenhorst?',
        answer: 'Einfache Websites: 3–5 Werktage. Business-Websites: 1–3 Wochen. Wir liefern schnell ohne Qualitätsverlust.' },
    ],
    relatedPages: [
      { title: 'Webdesign Bremen', href: '/webdesign-bremen' },
      { title: 'SEO-Agentur Delmenhorst', href: '/seo-agentur-delmenhorst' },
      { title: 'Leadgenerierung Delmenhorst', href: '/leadgenerierung-delmenhorst' },
      { title: 'Webdesign Kosten Delmenhorst', href: '/webdesign-kosten-delmenhorst' },
      { title: 'Online-Sichtbarkeit Delmenhorst', href: '/online-sichtbarkeit-delmenhorst' },
    ],
  },

  {
    slug: 'digitalisierung-delmenhorst',
    service: 'Digitalisierung',
    city: 'Delmenhorst',
    metaTitle: 'Digitalisierung Delmenhorst – KMU digital transformieren | Northcode',
    metaDescription: 'Digitalisierung für Unternehmen in Delmenhorst: Cloud, Prozessoptimierung & digitale Infrastruktur mit Förderberatung. Jetzt kostenlos beraten lassen!',
    h1: 'Digitalisierung in Delmenhorst',
    subtitle: 'Digital durchstarten – mit Plan und regionaler Unterstützung.',
    intro: 'Die Digitalisierung in Delmenhorst ist für viele Betriebe ein Riesenberg – unübersichtlich und teuer wirkend. Northcode macht sie planbar und erschwinglich: mit konkretem Fahrplan, priorisierten Maßnahmen und Hilfe bei der Beantragung von Fördermitteln.',
    stats: [
      { value: '35 %', label: 'Effizienzgewinn im Schnitt' },
      { value: '15–40 %', label: 'Fördermittelquote möglich' },
      { value: '6 Wo', label: 'bis zum digitalen Büro' },
      { value: '0 €', label: 'Erstgespräch & Fördercheck' },
    ],
    services: [
      { icon: '☁️', title: 'Cloud-Einführung', desc: 'Sichere Cloud-Umgebung für Ihre Daten und Zusammenarbeit – Microsoft 365 oder eigene Cloud.' },
      { icon: '📋', title: 'Papierloses Büro', desc: 'Digitale Ablage, automatische Belegerfassung und digitale Signaturen statt Papierstapel.' },
      { icon: '📱', title: 'Mobile Workforce', desc: 'Mitarbeiter arbeiten sicher von unterwegs – mit den richtigen Tools und Richtlinien.' },
      { icon: '🔌', title: 'Software-Integration', desc: 'Bestehende Software-Silos verbinden – kein manueller Datenaustausch mehr.' },
    ],
    benefits: [
      { title: 'Effizienzgewinn', desc: 'Digitale Prozesse sind messbar schneller und fehlerärmer als analoge.' },
      { title: 'Förderbar', desc: 'Bis zu 40 % der Investition durch "Digital Jetzt" und Niedersachsen-Förderprogramme erstattungsfähig.' },
      { title: 'Zukunftssicher', desc: 'Solide digitale Basis für spätere KI- und Automatisierungsmaßnahmen.' },
      { title: 'Persönlich begleitet', desc: 'Northcode ist regional verwurzelt – persönliche Beratung vor Ort in Delmenhorst.' },
    ],
    processSteps: [
      { step: 1, title: 'Status-Quo-Analyse', desc: 'Bestandsaufnahme aller Prozesse, Systeme und Schwachstellen Ihres Delmenhorster Betriebs.' },
      { step: 2, title: 'Digitalisierungs-Plan', desc: 'Priorisierter Maßnahmenplan mit Quick Wins und strategischen Schritten.' },
      { step: 3, title: 'Förderantrag', desc: 'Prüfung und Beantragung passender Förderprogramme.' },
      { step: 4, title: 'Umsetzung & Schulung', desc: 'Iterative Implementierung und Schulung aller Mitarbeiter.' },
    ],
    caseStudy: {
      result: 'Delmenhorster Handwerksbetrieb – vollständiges digitales Büro in 5 Wochen',
      description: 'Ein Handwerksbetrieb (15 Mitarbeiter) aus Delmenhorst arbeitete noch vollständig analog. Nach 5 Wochen Digitalisierungsprojekt: 50 % weniger Verwaltungsaufwand, papierloses Büro, 3.200 € Fördermittel erhalten.',
      m1: '50 %', m1Label: 'weniger Verwaltungsaufwand',
      m2: '3.200 €', m2Label: 'Fördermittel erhalten',
    },
    faqs: [
      { question: 'Welche Fördermittel gibt es für Digitalisierung in Delmenhorst?',
        answer: '"Digital Jetzt" (Bundesministerium) fördert mit 15–40 % der Investitionssumme. Northcode übernimmt die Antragstellung kostenlos für alle Projektkunden.' },
      { question: 'Was ist der erste Schritt für Digitalisierung in Delmenhorst?',
        answer: 'Das kostenlose Erstgespräch mit Northcode. In 45 Minuten analysieren wir gemeinsam Ihren größten Hebel und welche Maßnahme den schnellsten ROI bringt.' },
    ],
    relatedPages: [
      { title: 'Digitalisierung Bremen', href: '/digitalisierung-bremen' },
      { title: 'Digitalisierung Büro Delmenhorst', href: '/digitalisierung-buero-delmenhorst' },
      { title: 'Automatisierung kleine Unternehmen Delmenhorst', href: '/automatisierung-kleine-unternehmen-delmenhorst' },
      { title: 'Digitalisierung Kosten Delmenhorst', href: '/digitalisierung-kosten-delmenhorst' },
      { title: 'Digitalisierung Ganderkesee', href: '/digitalisierung-ganderkesee' },
    ],
  },

  {
    slug: 'imagefilm-delmenhorst',
    service: 'Imagefilm',
    city: 'Delmenhorst',
    metaTitle: 'Imagefilm Delmenhorst – Professionelle Unternehmensvideos | Northcode',
    metaDescription: 'Professionelle Imagefilme und Unternehmensvideos für Delmenhorst: Storytelling, Produktion & Distribution. Ihr Unternehmen auf dem nächsten Level. Jetzt anfragen!',
    h1: 'Imagefilm in Delmenhorst',
    subtitle: 'Ihr Unternehmen – professionell und emotional inszeniert.',
    intro: 'Ein professioneller Imagefilm zeigt potenziellen Kunden und Mitarbeitern in Delmenhorst, wer Sie wirklich sind – Ihre Werte, Ihre Stärken, Ihr Team. Northcode produziert Imagefilme, die bewegen und überzeugen.',
    stats: [
      { value: '3×', label: 'mehr Bewerbungen mit Imagefilm' },
      { value: '80 %', label: 'der Nutzer schauen Videos lieber' },
      { value: '2 Tage', label: 'typische Produktionsdauer vor Ort' },
      { value: '0 €', label: 'Erstgespräch & Konzeptidee' },
    ],
    services: [
      { icon: '🎬', title: 'Unternehmensfilm', desc: 'Professioneller Imagefilm für Website, Social Media und Messen – erzählt Ihre Geschichte überzeugend.' },
      { icon: '📣', title: 'Employer-Branding-Video', desc: 'Recruiting-Videos, die die richtigen Bewerber ansprechen und Delmenhorst als guten Arbeitsort zeigen.' },
      { icon: '🎥', title: 'Produkt- & Servicevideos', desc: 'Erklärvideos und Produktpräsentationen, die Kunden überzeugen.' },
      { icon: '📱', title: 'Social-Media-Content', desc: 'Kurze, plattformoptimierte Video-Clips für Instagram, LinkedIn und YouTube.' },
    ],
    benefits: [
      { title: 'Mehr Kunden', desc: 'Unternehmen mit Imagefilm werden häufiger kontaktiert – Vertrauen entsteht schneller.' },
      { title: 'Bessere Bewerber', desc: 'Ein gutes Employer-Branding-Video zieht qualifiziertere Bewerbungen an.' },
      { title: 'Multi-Channel', desc: 'Ein Imagefilm – vielseitig einzusetzen auf Website, Social Media und Messen.' },
      { title: 'Professioneller Auftritt', desc: 'Video-Präsenz signalisiert Kompetenz und Seriosität – auch für Delmenhorster KMU.' },
    ],
    processSteps: [
      { step: 1, title: 'Konzept & Briefing', desc: 'Ziele, Zielgruppe und Kernbotschaft klären – die Basis für ein überzeugendes Ergebnis.' },
      { step: 2, title: 'Drehbuch & Planung', desc: 'Skript, Drehorte in Delmenhorst, Besetzung und Ablaufplan.' },
      { step: 3, title: 'Produktion', desc: 'Professioneller Drehtag vor Ort mit 4K-Equipment und erfahrenem Filmteam.' },
      { step: 4, title: 'Post-Produktion & Auslieferung', desc: 'Schnitt, Farbkorrektur, Musik, Sprecher und Auslieferung in allen Formaten.' },
    ],
    caseStudy: {
      result: 'Delmenhorster Produktionsunternehmen – 40 % mehr Anfragen nach Imagefilm',
      description: 'Ein Produktionsunternehmen aus Delmenhorst veröffentlichte einen Imagefilm auf Website und LinkedIn. Im ersten Monat: 40 % mehr Kundenanfragen und 3× mehr qualifizierte Bewerbungen.',
      m1: '+40 %', m1Label: 'mehr Kundenanfragen',
      m2: '3×', m2Label: 'mehr qualifizierte Bewerbungen',
    },
    faqs: [
      { question: 'Was kostet ein Imagefilm in Delmenhorst?',
        answer: 'Einfache Imagefilme (1–2 Min., 1 Drehtag): 1.500–3.000 €. Professionelle Unternehmensfilme mit Sprecher, Musik und Grafiken: 3.000–7.000 €.' },
      { question: 'Muss ich einen Sprecher bereitstellen?',
        answer: 'Nein. Northcode hat ein Netzwerk professioneller Off-Sprecher für alle Stilrichtungen.' },
    ],
    relatedPages: [
      { title: 'Imagefilm Bremen', href: '/imagefilm-bremen' },
      { title: 'Webdesign Delmenhorst', href: '/webdesign-delmenhorst' },
      { title: 'KI-Automatisierung Delmenhorst', href: '/ki-automatisierung-delmenhorst' },
    ],
  },

  {
    slug: 'ki-beratung-delmenhorst',
    service: 'KI-Beratung',
    city: 'Delmenhorst',
    metaTitle: 'KI-Beratung Delmenhorst – KI-Strategie für Ihr Unternehmen | Northcode',
    metaDescription: 'KI-Beratung für Unternehmen in Delmenhorst: KI-Strategie, Use-Case-Analyse & Implementierungsbegleitung. Pragmatisch und umsetzungsorientiert. Jetzt anfragen!',
    h1: 'KI-Beratung in Delmenhorst',
    subtitle: 'KI-Strategie, die wirklich umgesetzt wird – nicht nur präsentiert.',
    intro: 'KI-Beratung in Delmenhorst bedeutet bei Northcode keine abstrakten Strategiepapiere – sondern konkrete Use-Cases, klare Prioritäten und direkte Umsetzungsbegleitung. Wir zeigen Ihnen, wo KI in Ihrem Unternehmen wirklich Sinn macht.',
    stats: [
      { value: '3–5', label: 'KI-Use-Cases pro Unternehmen' },
      { value: '< 4 Wo', label: 'bis zum ersten KI-Piloten live' },
      { value: '100 %', label: 'umsetzungsorientierte Beratung' },
      { value: '0 €', label: 'Erstgespräch & KI-Potenzialcheck' },
    ],
    services: [
      { icon: '🎯', title: 'KI-Potenzialanalyse', desc: 'Systematische Analyse Ihrer Prozesse auf KI-Automatisierungspotenzial mit ROI-Kalkulation.' },
      { icon: '📋', title: 'KI-Strategie', desc: 'Priorisierter Umsetzungsplan mit konkreten Maßnahmen, Timings und Budgets.' },
      { icon: '🔧', title: 'Tool-Auswahl', desc: 'Welche KI-Tools passen zu Ihrem Unternehmen? ChatGPT, Make, n8n oder Individuallösung?' },
      { icon: '🚀', title: 'Pilotprojekt-Begleitung', desc: 'Von der ersten Idee bis zum laufenden KI-System – Northcode begleitet die gesamte Umsetzung.' },
    ],
    benefits: [
      { title: 'Pragmatisch', desc: 'Keine Buzzword-Bingo – konkrete Use-Cases mit echten ROI-Zahlen für Ihr Unternehmen.' },
      { title: 'Regional', desc: 'Northcode ist persönlich vor Ort in Delmenhorst – kein anonymes Beratungsunternehmen.' },
      { title: 'Schnell', desc: 'Erster Pilot in 2–4 Wochen live – keine monatelangen Strategieprojekte.' },
      { title: 'Umsetzend', desc: 'Northcode berät nicht nur – wir bauen die Systeme auch. Aus einer Hand.' },
    ],
    processSteps: [
      { step: 1, title: 'KI-Workshop (90 Min.)', desc: 'Gemeinsame Analyse Ihrer Prozesse und Identifikation der besten KI-Use-Cases für Delmenhorst.' },
      { step: 2, title: 'Potenzial-Report', desc: 'Schriftlicher Bericht mit priorisierten Use-Cases, ROI-Kalkulation und Umsetzungsvorschlägen.' },
      { step: 3, title: 'Pilot-Definition & Bau', desc: 'Auswahl und Entwicklung des ersten KI-Piloten in Ihrem Unternehmen.' },
      { step: 4, title: 'Evaluation & Skalierung', desc: 'Messung der Ergebnisse und Entscheidung über Skalierung weiterer Use-Cases.' },
    ],
    caseStudy: {
      result: 'Delmenhorster Dienstleistungsbetrieb – 4 KI-Use-Cases, Pilot in 3 Wochen live',
      description: 'Ein Dienstleistungsbetrieb aus Delmenhorst buchte den KI-Workshop von Northcode. Innerhalb von 90 Minuten wurden 4 konkrete Use-Cases identifiziert. Das Pilotprojekt (automatische Angeboterstellung) ging 3 Wochen später live.',
      m1: '4', m1Label: 'KI-Use-Cases identifiziert',
      m2: '3 Wo', m2Label: 'bis zum Piloten live',
    },
    faqs: [
      { question: 'Lohnt sich KI-Beratung für kleine Unternehmen in Delmenhorst?',
        answer: 'Ja – gerade für KMU. Northcode bietet einen kompakten 90-Minuten-KI-Workshop für 490 €, der klare Antworten liefert: Wo lohnt sich KI in Ihrem Betrieb – und wo nicht.' },
      { question: 'Was wenn wir nach der Beratung nichts umsetzen wollen?',
        answer: 'Kein Problem. Die Beratungsleistung ist ein eigenständiges Produkt ohne Umsetzungsverpflichtung.' },
    ],
    relatedPages: [
      { title: 'KI-Beratung Oldenburg', href: '/ki-beratung-oldenburg' },
      { title: 'KI-Automatisierung Bremen', href: '/ki-automatisierung-bremen' },
      { title: 'KI für Handwerker Delmenhorst', href: '/ki-fuer-handwerker-delmenhorst' },
      { title: 'KI für Gastronomie Delmenhorst', href: '/ki-fuer-gastronomie-delmenhorst' },
      { title: 'Kundenanfragen automatisieren Delmenhorst', href: '/kundenanfragen-automatisieren-delmenhorst' },
    ],
  },

  /* ── GANDERKESEE (+6) ───────────────────────────────────────────────────── */
  {
    slug: 'ki-automatisierung-ganderkesee',
    service: 'KI-Automatisierung',
    city: 'Ganderkesee',
    metaTitle: 'KI-Automatisierung Ganderkesee – KI für Betriebe in der Region | Northcode',
    metaDescription: 'KI-Automatisierung für Unternehmen in Ganderkesee & Landkreis Oldenburg: Chatbots, Dokumenten-KI & Workflow-Automation. Persönliche Betreuung. Jetzt anfragen!',
    h1: 'KI-Automatisierung in Ganderkesee',
    subtitle: 'KI für Betriebe in der Gemeinde Ganderkesee – praktisch und erschwinglich.',
    intro: 'In Ganderkesee und dem Landkreis Oldenburg bietet KI-Automatisierung für Betriebe eine einzigartige Chance: Wettbewerber sind digital oft noch wenig aufgestellt. Northcode bringt KI-Technologie zu Betrieben in der Region – persönlich, pragmatisch und erschwinglich.',
    stats: [
      { value: '80 %', label: 'der Routineaufgaben automatisierbar' },
      { value: '2–3 Mo', label: 'typische Amortisationszeit' },
      { value: '24/7', label: 'KI arbeitet ohne Pause' },
      { value: '0 €', label: 'Erstgespräch & KI-Check' },
    ],
    services: [
      { icon: '🤖', title: 'KI-Chatbots', desc: 'Intelligente Chatbots für Ihre Website oder WhatsApp – beantworten Fragen rund um die Uhr.' },
      { icon: '📂', title: 'Dokument-KI', desc: 'Automatische Erkennung und Verarbeitung von Belegen, Formularen und Dokumenten.' },
      { icon: '🔄', title: 'Workflow-Automation', desc: 'Wiederkehrende Abläufe vollständig automatisieren – von der Anfrage bis zur Rechnung.' },
      { icon: '📊', title: 'KI-Reporting', desc: 'Automatische Berichte und Auswertungen aus Ihren Unternehmensdaten.' },
    ],
    benefits: [
      { title: 'Rund um die Uhr', desc: 'KI-Systeme arbeiten 24/7 – auch wenn Sie nicht da sind.' },
      { title: 'Lernend', desc: 'Moderne KI verbessert sich automatisch mit jedem Einsatz.' },
      { title: 'Erschwinglich', desc: 'Einstiegslösungen ab 600 € – auch für kleine Betriebe in Ganderkesee finanzierbar.' },
      { title: 'Persönlich', desc: 'Northcode kommt persönlich zu Ihnen in die Gemeinde Ganderkesee.' },
    ],
    processSteps: [
      { step: 1, title: 'KI-Check', desc: 'Kostenlose Analyse: welche Prozesse in Ihrem Ganderkeseer Betrieb sind KI-automatisierbar?' },
      { step: 2, title: 'Konzept', desc: 'Auswahl der optimalen KI-Lösung für Ihren Anwendungsfall und Ihr Budget.' },
      { step: 3, title: 'Entwicklung & Integration', desc: 'Bau und Einbindung der KI-Systeme in Website, CRM oder bestehende Tools.' },
      { step: 4, title: 'Schulung & Support', desc: 'Einweisung aller Mitarbeiter und dauerhafter Ansprechpartner bei Northcode.' },
    ],
    caseStudy: {
      result: 'Handwerksbetrieb Landkreis Oldenburg – 8h Büroarbeit pro Woche gespart',
      description: 'Ein Handwerksbetrieb in der Gemeinde Ganderkesee ließ Terminbuchung und Angebotsversand vollautomatisieren. Ergebnis: 8 Stunden Büroarbeit pro Woche eingespart, in 3 Wochen produktiv.',
      m1: '8h/Wo', m1Label: 'Büroarbeit eingespart',
      m2: '3 Wo', m2Label: 'bis zur Automatisierung live',
    },
    faqs: [
      { question: 'Kommt Northcode auch nach Ganderkesee?',
        answer: 'Ja. Als regionaler Anbieter kommen wir persönlich zu Ihnen – ob Ganderkesee, Bookholzberg, Schierbrok oder andere Ortsteile der Gemeinde.' },
      { question: 'Was kostet KI-Automatisierung für Betriebe in Ganderkesee?',
        answer: 'Einstiegslösungen ab 600 €. Vollständige Automatisierungssysteme ab 1.500 €. Im kostenlosen Erstgespräch erhalten Sie eine konkrete Kalkulation.' },
    ],
    relatedPages: [
      { title: 'KI-Automatisierung Bremen', href: '/ki-automatisierung-bremen' },
      { title: 'KI kleine Unternehmen Ganderkesee', href: '/ki-kleine-unternehmen-ganderkesee' },
      { title: 'Automatisierung Handwerk Ganderkesee', href: '/automatisierung-handwerk-ganderkesee' },
      { title: 'Kundenanfragen automatisieren Ganderkesee', href: '/kundenanfragen-automatisieren-ganderkesee' },
      { title: 'Chatbot kleine Firmen Ganderkesee', href: '/chatbot-kleine-firmen-ganderkesee' },
    ],
  },

  {
    slug: 'webdesign-ganderkesee',
    service: 'Webdesign',
    city: 'Ganderkesee',
    metaTitle: 'Webdesign Ganderkesee – Professionelle Website für Ihren Betrieb | Northcode',
    metaDescription: 'Professionelles Webdesign für Betriebe in Ganderkesee & Landkreis Oldenburg: moderne Website, lokales SEO & persönliche Betreuung. Jetzt anfragen!',
    h1: 'Webdesign in Ganderkesee',
    subtitle: 'Ihre professionelle Online-Präsenz in der Gemeinde Ganderkesee.',
    intro: 'In Ganderkesee und dem Landkreis Oldenburg sind viele Unternehmen noch nicht oder nur mit veralteten Websites online. Das ist eine Riesenchance für alle, die jetzt eine professionelle Online-Präsenz aufbauen. Northcode entwickelt Ihre Website – persönlich, schnell und für die Region optimiert.',
    stats: [
      { value: '100+', label: 'Websites realisiert in der Region' },
      { value: '< 3 Sek', label: 'Ladezeit-Ziel' },
      { value: '3×', label: 'mehr Anfragen mit guter Website' },
      { value: '0 €', label: 'Erstgespräch & Konzeptidee' },
    ],
    services: [
      { icon: '💻', title: 'Business-Websites', desc: 'Professionelle Unternehmenswebsites für Ganderkeseer Betriebe aller Branchen.' },
      { icon: '🎯', title: 'Landingpages', desc: 'Conversion-optimierte Seiten für konkrete Angebote und Kampagnen.' },
      { icon: '🔍', title: 'Lokales SEO', desc: 'Optimierung für "Service + Ganderkesee"-Suchanfragen bei Google.' },
      { icon: '📱', title: 'Mobile-First', desc: 'Perfektes Erlebnis auf Smartphones – die meisten Anfragen kommen vom Handy.' },
    ],
    benefits: [
      { title: 'Lokal gefunden', desc: 'Optimiert für Suchanfragen aus Ganderkesee und dem Landkreis Oldenburg.' },
      { title: 'Mobil perfekt', desc: 'Mehr als 70 % der Nutzer suchen auf dem Smartphone.' },
      { title: 'Schnell', desc: 'Optimierte Ladezeiten für bessere Rankings und weniger Absprünge.' },
      { title: 'Selbst pflegbar', desc: 'CMS-Zugang für eigene Textupdates – keine Technik-Kenntnisse notwendig.' },
    ],
    processSteps: [
      { step: 1, title: 'Persönliches Briefing', desc: 'Kennenlernen vor Ort in Ganderkesee oder per Video-Call.' },
      { step: 2, title: 'Konzept & Design', desc: 'Designentwurf und Struktur – Sie sehen früh das Ergebnis.' },
      { step: 3, title: 'Entwicklung & SEO', desc: 'Technische Umsetzung mit SEO-Grundoptimierung für Ganderkesee.' },
      { step: 4, title: 'Launch & Support', desc: 'Go-Live, Google-Anmeldung, Einweisung und 30 Tage Support.' },
    ],
    caseStudy: {
      result: 'Handwerksbetrieb Ganderkesee – erste Google-Rankings in 4 Wochen',
      description: 'Ein Handwerksbetrieb in Ganderkesee hatte keine eigene Website. Northcode entwickelte eine mobiloptimierte Business-Website. Nach 4 Wochen erste Google-Rankings für lokale Suchbegriffe – seitdem 2 Neukundenanfragen pro Woche über die Website.',
      m1: '4 Wo', m1Label: 'erste Google-Rankings',
      m2: '2/Wo', m2Label: 'neue Kundenanfragen über Website',
    },
    faqs: [
      { question: 'Was kostet eine Website für meinen Betrieb in Ganderkesee?',
        answer: 'Einfache Seite: ab 390 €. Business-Website mit SEO: ab 900 €. Im kostenlosen Erstgespräch erhalten Sie ein transparentes Festpreisangebot.' },
      { question: 'Kann ich die Website danach selbst bearbeiten?',
        answer: 'Ja – alle Websites liefern wir mit CMS-Zugang. Texte, Bilder und Preise können Sie selbst ändern.' },
    ],
    relatedPages: [
      { title: 'Webdesign Bremen', href: '/webdesign-bremen' },
      { title: 'Website lokale Firmen Ganderkesee', href: '/website-lokale-firmen-ganderkesee' },
      { title: 'Online-Sichtbarkeit Ganderkesee', href: '/online-sichtbarkeit-ganderkesee' },
      { title: 'Lokale SEO Ganderkesee', href: '/lokale-seo-ganderkesee' },
      { title: 'Webdesign Kosten Ganderkesee', href: '/webdesign-kosten-ganderkesee' },
    ],
  },

  {
    slug: 'prozessautomatisierung-ganderkesee',
    service: 'Prozessautomatisierung',
    city: 'Ganderkesee',
    metaTitle: 'Prozessautomatisierung Ganderkesee – Workflows automatisieren | Northcode',
    metaDescription: 'Prozessautomatisierung für Betriebe in Ganderkesee: manuelle Workflows eliminieren & Effizienz steigern. Persönliche Betreuung im Landkreis Oldenburg. Jetzt anfragen!',
    h1: 'Prozessautomatisierung in Ganderkesee',
    subtitle: 'Routineaufgaben eliminieren – mehr Zeit für Ihr Kerngeschäft.',
    intro: 'Betriebe in Ganderkesee und dem Landkreis Oldenburg verlieren täglich Zeit mit wiederkehrenden Verwaltungsaufgaben. Prozessautomatisierung schafft Kapazitäten für das, was wirklich wichtig ist – und Northcode baut die passenden Systeme.',
    stats: [
      { value: '70 %', label: 'weniger Routineaufgaben' },
      { value: '< 3 Wo', label: 'bis zum ersten Ergebnis' },
      { value: '5×', label: 'ROI typisch im ersten Jahr' },
      { value: '0 €', label: 'Erstgespräch & Analyse' },
    ],
    services: [
      { icon: '🔄', title: 'Workflow-Automatisierung', desc: 'Manuelle Abläufe zwischen Systemen automatisch orchestrieren.' },
      { icon: '📊', title: 'Automatisches Reporting', desc: 'Tägliche Berichte und KPIs automatisch generieren.' },
      { icon: '🔌', title: 'System-Integration', desc: 'Bestehende Software-Tools verbinden – kein manueller Datenaustausch mehr.' },
      { icon: '🤖', title: 'KI-Workflows', desc: 'Intelligente Prozesse mit KI-Unterstützung für komplexere Entscheidungen.' },
    ],
    benefits: [
      { title: 'Sofortige Wirkung', desc: 'Erste automatisierte Prozesse gehen innerhalb von Wochen live.' },
      { title: 'Fehlerfrei', desc: 'Automatisierte Prozesse sind konsistenter und fehlerarmer als manuelle.' },
      { title: 'Skalierbar', desc: 'Das System wächst mit Ihrem Ganderkeseer Betrieb mit.' },
      { title: 'Persönlich betreut', desc: 'Northcode betreut Sie persönlich – nicht anonym per Ticket-System.' },
    ],
    processSteps: [
      { step: 1, title: 'Prozess-Audit', desc: 'Analyse der größten Zeitfresser in Ihrem Betrieb in Ganderkesee.' },
      { step: 2, title: 'Prioritäten setzen', desc: 'Welche Prozesse bringen die größte Zeitersparnis pro Aufwand?' },
      { step: 3, title: 'Automatisierung bauen', desc: 'Entwicklung und Integration in bestehende Systeme.' },
      { step: 4, title: 'Go-Live & Schulung', desc: 'Inbetriebnahme und Einweisung aller betroffenen Mitarbeiter.' },
    ],
    caseStudy: {
      result: 'Dienstleister Landkreis Oldenburg – Auftragsabwicklung 6× schneller',
      description: 'Ein Dienstleistungsbetrieb in der Gemeinde Ganderkesee verarbeitete Aufträge manuell in 3 Stunden täglich. Nach Automatisierung durch Northcode: 30 Minuten statt 3 Stunden, ohne neue Mitarbeiter oder neue Software.',
      m1: '6×', m1Label: 'schnellere Auftragsabwicklung',
      m2: '0', m2Label: 'neue Mitarbeiter benötigt',
    },
    faqs: [
      { question: 'Was kostet Prozessautomatisierung in Ganderkesee?',
        answer: 'Einfache Automatisierungen ab 700 €. Komplexere Systeme ab 2.500 €. Im kostenlosen Erstgespräch erhalten Sie eine konkrete Kalkulation.' },
      { question: 'Muss ich meine bestehende Software wechseln?',
        answer: 'Nein. Northcode integriert in Ihre vorhandenen Systeme – egal welche Software Sie in Ganderkesee einsetzen.' },
    ],
    relatedPages: [
      { title: 'Prozessautomatisierung Bremen', href: '/prozessautomatisierung-bremen' },
      { title: 'Automatisierung Handwerk Ganderkesee', href: '/automatisierung-handwerk-ganderkesee' },
      { title: 'CRM-KMU Ganderkesee', href: '/crm-kmu-ganderkesee' },
      { title: 'Rechnungsautomatisierung Ganderkesee', href: '/rechnungsautomatisierung-ganderkesee' },
      { title: 'Business Automatisierung Ganderkesee', href: '/business-automatisierung-ganderkesee' },
    ],
  },

  {
    slug: 'imagefilm-ganderkesee',
    service: 'Imagefilm',
    city: 'Ganderkesee',
    metaTitle: 'Imagefilm Ganderkesee – Unternehmensvideos für die Region | Northcode',
    metaDescription: 'Professionelle Imagefilme für Betriebe in Ganderkesee & Landkreis Oldenburg: Storytelling, Produktion & Social Media. Jetzt kostenlos anfragen!',
    h1: 'Imagefilm in Ganderkesee',
    subtitle: 'Ihr Betrieb – professionell und authentisch auf Video.',
    intro: 'Ein Imagefilm zeigt Kunden und Mitarbeitern in Ganderkesee und dem Landkreis Oldenburg, wer Sie sind und warum sie mit Ihnen arbeiten sollten. Northcode produziert Videos, die echt wirken und echte Ergebnisse bringen.',
    stats: [
      { value: '3×', label: 'mehr Anfragen mit Imagefilm' },
      { value: '80 %', label: 'der Nutzer schauen Videos lieber' },
      { value: '2 Tage', label: 'typische Drehzeit' },
      { value: '0 €', label: 'Erstgespräch & Konzeptidee' },
    ],
    services: [
      { icon: '🎬', title: 'Unternehmensfilm', desc: 'Professioneller Imagefilm für Website und Social Media – erzählt Ihre Geschichte.' },
      { icon: '📣', title: 'Recruiting-Video', desc: 'Employer-Branding-Videos, die die richtigen Bewerber ansprechen.' },
      { icon: '🎥', title: 'Produkt-Videos', desc: 'Kurze Erklärvideos für Ihre Produkte oder Dienstleistungen.' },
      { icon: '📱', title: 'Social-Media-Clips', desc: 'Kurz und plattformoptimiert für Instagram, LinkedIn und YouTube.' },
    ],
    benefits: [
      { title: 'Mehr Vertrauen', desc: 'Video vermittelt Authentizität und Kompetenz schneller als Text.' },
      { title: 'Bessere Bewerber', desc: 'Ein gutes Recruiting-Video zieht die richtigen Kandidaten an.' },
      { title: 'Multi-Channel', desc: 'Ein Video – vielseitig einsetzbar auf allen Kanälen.' },
      { title: 'Persönlich', desc: 'Northcode dreht vor Ort in Ganderkesee – kein anonymes Produktionsteam.' },
    ],
    processSteps: [
      { step: 1, title: 'Konzept', desc: 'Ziele, Zielgruppe und Kernbotschaft klären.' },
      { step: 2, title: 'Drehplanung', desc: 'Drehorte in Ganderkesee, Ablauf und Besetzung festlegen.' },
      { step: 3, title: 'Produktion', desc: 'Professioneller Drehtag vor Ort in Ganderkesee.' },
      { step: 4, title: 'Post-Produktion & Auslieferung', desc: 'Schnitt, Musik, Vertonung und Auslieferung in allen Formaten.' },
    ],
    caseStudy: {
      result: 'Handwerksbetrieb Gemeinde Ganderkesee – 25 % mehr Anfragen nach Imagefilm',
      description: 'Ein Handwerksbetrieb in der Gemeinde Ganderkesee veröffentlichte einen Imagefilm auf Website und LinkedIn. Im ersten Monat: 25 % mehr Kundenanfragen und deutlich bessere Bewerbungsqualität.',
      m1: '+25 %', m1Label: 'mehr Kundenanfragen',
      m2: '2×', m2Label: 'bessere Bewerbungsqualität',
    },
    faqs: [
      { question: 'Was kostet ein Imagefilm in Ganderkesee?',
        answer: 'Einfache Videos ab 1.200 €. Professionelle Unternehmensfilme: 2.500–5.000 €. Im kostenlosen Erstgespräch erhalten Sie eine genaue Kalkulation.' },
    ],
    relatedPages: [
      { title: 'Imagefilm Bremen', href: '/imagefilm-bremen' },
      { title: 'Webdesign Ganderkesee', href: '/webdesign-ganderkesee' },
      { title: 'Digitalisierung Ganderkesee', href: '/digitalisierung-ganderkesee' },
    ],
  },

  {
    slug: 'unternehmenssysteme-ganderkesee',
    service: 'Unternehmenssysteme',
    city: 'Ganderkesee',
    metaTitle: 'Unternehmenssysteme Ganderkesee – Business-Software für KMU | Northcode',
    metaDescription: 'Individuelle Unternehmenssysteme für Betriebe in Ganderkesee: ERP, CRM & Business-Software ohne monatliche Lizenzkosten. Persönliche Betreuung. Jetzt anfragen!',
    h1: 'Unternehmenssysteme in Ganderkesee',
    subtitle: 'Business-Software für den Landkreis Oldenburg – ohne teure Abos.',
    intro: 'Betriebe in Ganderkesee und dem Landkreis Oldenburg zahlen oft monatlich für teure Standard-Software, die nur zu 30 % genutzt wird. Northcode entwickelt Systeme, die exakt zu Ihren Prozessen passen – einmalige Kosten, dauerhaft im Besitz.',
    stats: [
      { value: '100 %', label: 'nach Ihren Prozessen gebaut' },
      { value: '0 €', label: 'monatliche Lizenzkosten' },
      { value: '4–8 Wo', label: 'bis zur ersten Version' },
      { value: '0 €', label: 'Erstgespräch' },
    ],
    services: [
      { icon: '🏢', title: 'ERP-Systeme', desc: 'Warenwirtschaft, Buchhaltungsanbindung und Auftragsabwicklung in einer Lösung.' },
      { icon: '🔗', title: 'CRM-Software', desc: 'Kundenverwaltung und Vertriebspipeline – gebaut nach Ihrem Prozess.' },
      { icon: '📦', title: 'Lagerverwaltung', desc: 'Bestandskontrolle, Lieferantenbestellungen und Inventar digital managen.' },
      { icon: '📊', title: 'Reporting-Dashboards', desc: 'Echtzeit-Einblick in alle wichtigen Kennzahlen Ihres Betriebs.' },
    ],
    benefits: [
      { title: 'Passgenaue Lösung', desc: 'Software, die Ihren Prozess abbildet – nicht Sie zwingt, sich anzupassen.' },
      { title: 'Keine Abonnements', desc: 'Einmalige Entwicklungskosten – das System gehört Ihnen dauerhaft.' },
      { title: 'Vollintegriert', desc: 'Anbindung an DATEV, E-Mail, Webshop oder andere Tools.' },
      { title: 'Persönliche Betreuung', desc: 'Northcode ist regional – persönlicher Ansprechpartner, kein anonymer Support.' },
    ],
    processSteps: [
      { step: 1, title: 'Anforderungs-Briefing', desc: 'Gründliche Aufnahme aller Anforderungen und Wünsche Ihres Ganderkeseer Betriebs.' },
      { step: 2, title: 'Konzept', desc: 'Systemarchitektur und Funktionsumfang definieren.' },
      { step: 3, title: 'Iterative Entwicklung', desc: 'Entwicklung in Sprints – Sie sehen früh erste Ergebnisse.' },
      { step: 4, title: 'Launch, Datenmigration & Support', desc: 'Go-Live, Übernahme bestehender Daten, Schulung und dauerhafter Support.' },
    ],
    caseStudy: {
      result: 'Einzelhandel Gemeinde Ganderkesee – Warenverwaltung und CRM konsolidiert',
      description: 'Ein Einzelhändler in der Gemeinde Ganderkesee pflegte Waren und Kunden in separaten Systemen. Northcode entwickelte eine integrierte Lösung – 30 % schnellere Auftragsabwicklung, Fehlerquote auf null.',
      m1: '30 %', m1Label: 'schnellere Auftragsabwicklung',
      m2: '0', m2Label: 'Buchungsfehler nach Einführung',
    },
    faqs: [
      { question: 'Was kostet ein individuelles Unternehmenssystem in Ganderkesee?',
        answer: 'Basis-System (Kontakt- und Auftragsverwaltung): ab 1.800 €. Vollständiges ERP mit Integrationen: 4.000–10.000 €. Keine monatlichen Lizenzgebühren danach.' },
    ],
    relatedPages: [
      { title: 'Unternehmenssysteme Bremen', href: '/unternehmenssysteme-bremen' },
      { title: 'CRM-KMU Ganderkesee', href: '/crm-kmu-ganderkesee' },
      { title: 'Digitalisierung Büro Ganderkesee', href: '/digitalisierung-buero-ganderkesee' },
      { title: 'Kundenverwaltung digital Ganderkesee', href: '/kundenverwaltung-digital-ganderkesee' },
    ],
  },

  {
    slug: 'backend-entwicklung-ganderkesee',
    service: 'Backend-Entwicklung',
    city: 'Ganderkesee',
    metaTitle: 'Backend-Entwicklung Ganderkesee – APIs & Server für KMU | Northcode',
    metaDescription: 'Professionelle Backend-Entwicklung für Betriebe in Ganderkesee: APIs, Datenbanken & Server-Systeme. Skalierbar, sicher & regional betreut. Jetzt anfragen!',
    h1: 'Backend-Entwicklung in Ganderkesee',
    subtitle: 'Solide technische Grundlage für digitale Geschäftssysteme.',
    intro: 'Ob Web-App, Mobile App oder Unternehmensportal – das Backend entscheidet über Performance, Sicherheit und Skalierbarkeit. Northcode entwickelt Backend-Systeme für Betriebe in Ganderkesee und dem Landkreis Oldenburg – mit regionalem Support.',
    stats: [
      { value: '99,9 %', label: 'angestrebte Uptime' },
      { value: '< 200ms', label: 'API-Antwortzeit (Ziel)' },
      { value: '10+', label: 'Systeme in der Region entwickelt' },
      { value: '0 €', label: 'Erstgespräch' },
    ],
    services: [
      { icon: '🔗', title: 'REST & GraphQL APIs', desc: 'Skalierbare APIs für alle Art von Anwendungen und Integrationen.' },
      { icon: '🗄️', title: 'Datenbank-Design', desc: 'Optimierte Datenbankstrukturen für Performance und Sicherheit.' },
      { icon: '☁️', title: 'Cloud-Infrastruktur', desc: 'Serverarchitektur für maximale Uptime und Kosteneffizienz.' },
      { icon: '🛡️', title: 'DSGVO-Compliance', desc: 'Datenschutzkonforme Backend-Systeme mit deutschen Serveroptionen.' },
    ],
    benefits: [
      { title: 'Schnell & performant', desc: 'Optimierte Backend-Systeme für blitzschnelle Antwortzeiten.' },
      { title: 'Sicher by Design', desc: 'DSGVO-konform von Anfang an.' },
      { title: 'Skalierbar', desc: 'Wächst mit Ihrem Unternehmen – ohne Neubau.' },
      { title: 'Regional betreut', desc: 'Northcode ist Ihr langfristiger technischer Partner in der Region.' },
    ],
    processSteps: [
      { step: 1, title: 'Technisches Briefing', desc: 'Anforderungen, Schnittstellen und Skalierungsziele klären.' },
      { step: 2, title: 'Architektur', desc: 'Optimale Technologien und Systemarchitektur auswählen.' },
      { step: 3, title: 'Entwicklung & Testing', desc: 'Iterative Entwicklung: Performance-, Sicherheits- und Integrationstests.' },
      { step: 4, title: 'Deployment & Monitoring', desc: 'Live-Schaltung und 24/7 Monitoring.' },
    ],
    caseStudy: {
      result: 'Web-App Betreiber Landkreis Oldenburg – API-Performance verdreifacht',
      description: 'Ein Web-App-Betreiber im Landkreis Oldenburg kämpfte mit langsamen API-Antworten und Ausfällen unter Last. Northcode redesignte die Backend-Architektur – Antwortzeiten von 800ms auf unter 200ms, das System skaliert nun auf 5× mehr Nutzer.',
      m1: '3×', m1Label: 'schnellere API-Performance',
      m2: '5×', m2Label: 'mehr Nutzer ohne Probleme',
    },
    faqs: [
      { question: 'Was kostet Backend-Entwicklung in Ganderkesee?',
        answer: 'Einfache API: ab 1.500 €. Komplexe Backend-Systeme: 5.000–20.000 €. Im kostenlosen Erstgespräch erhalten Sie eine genaue Einschätzung.' },
    ],
    relatedPages: [
      { title: 'Backend-Entwicklung Bremen', href: '/backend-entwicklung-bremen' },
      { title: 'KI-Automatisierung Ganderkesee', href: '/ki-automatisierung-ganderkesee' },
      { title: 'Unternehmenssysteme Ganderkesee', href: '/unternehmenssysteme-ganderkesee' },
    ],
  },
];

export const extraPillarSlugs = extraPillarPages.map(p => p.slug);
